### ISSUE TITLE
"Merging" hyperlink on GitHub links to incorrect section of the archive.

### ISSUE THREAD

**Issue by Haaaaaaaa615** [Soontech-Annals/Archive#1]
In the README, the merging hyperlink goes to "https://github.com/Soontech-Annals/Archive/blob/main/Archive/logic-and-computation" instead of "https://github.com/Soontech-Annals/Archive/tree/main/Archive/merging".

**Comment by Andrews54757** [comment]
ty, will fix in 2023 issue
